sudo: required
services:
    docker

before_install:
    - docker build -t aleksejtodorovic/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aleksejtodorovic/react-test npm test -- --coverage

after_success:
    - docker build -t aleksejtodorovic/multi-client ./client
    - docker build -t aleksejtodorovic/multi-nginx ./nginx
    - docker build -t aleksejtodorovic/multi-server ./server
    - docker build -t aleksejtodorovic/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push them to docker hub
    - docker push aleksejtodorovic/multi-client
    - docker push aleksejtodorovic/multi-nginx
    - docker push aleksejtodorovic/multi-server
    - docker push aleksejtodorovic/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-456505254913"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY